#' Simulation Data Generation
#'
#' Generate simulation data of ground motion residuals with event, site, and single station within event residuals.
#'
#' @param num_event The integer to specify the number of earthquake events.
#' @param num_site The integer to specify the number of earthquake station sites.
#' @param tau The numeric value to specify the standard deviation of event terms.
#' @param phi_S2S The numeric value specify the standard deviation of site terms.
#' @param phi_SS The numeric value specify the standard deviation of single station within event residuals.
#' @param path_term A logical indicator for whether to generate path term.
#' @param phi_P2P The numeric value to specify the standard deviation of path terms.
#' @param num_event_cluster The integer to specify the number of earthquakes event clusters.
#' @param num_site_cluster The integer to specify the number of earthquakes station site clusters.
#' @param missing_percent A decimal between 0 and 1, indicating the percentage of
#'                        missingness generated by missing completely at random(MCAR).
#'
#' @return A data frame containing the full simulation dataset.
#' @export
#'
#' @examples
#' gm_data <- dgp(num_event = 10, num_site = 20,
#'                tau = 1, phi_S2S = 1, phi_SS = 1)
dgp <- function(num_event, num_site,
                tau = 1, phi_S2S = 1, phi_SS = 1,
                path_term = FALSE, phi_P2P = NULL,
                num_event_cluster = NULL, num_site_cluster = NULL,
                missing_percent = 0){

  delta_B <- rep(rnorm(num_event, mean=0, sd=tau), each = num_site)
  event_id <- as.factor(rep(1:num_event, each = num_site))


  delta_S2S <- rep(rnorm(num_site, mean = 0, sd = phi_S2S), num_event)
  site_id <- as.factor(rep(1:num_site, num_event))

  delta_WS <- rnorm(num_event*num_site, mean=0, sd=phi_SS)

  r <- delta_B + delta_S2S + delta_WS

  if(path_term == TRUE){
    event_cluster <- sample(1:num_event_cluster, num_event, replace = TRUE)
    event_cluster_id <- sapply(event_id, function(x) event_cluster[x])

    site_cluster <- sample(1:num_site_cluster, num_site, replace = TRUE)
    site_cluster_id <- sapply(site_id, function(x) site_cluster[x])

    path_id <- as.numeric(factor(paste(event_cluster_id, site_cluster_id)))
    path_value <- rnorm(max(path_id), mean = 0, sd = phi_P2P)
    delta_P2P <- sapply(path_id, function(x) path_value[x])
    path_id <- as.factor(path_id)

    r <- delta_B + delta_S2S + delta_P2P + delta_WS
  }

  if(path_term == TRUE){
    data <- data.frame(r, delta_B, delta_S2S, delta_P2P, delta_WS,
               event_id, site_id, path_id)
  }else{
    data <- data.frame(r, delta_B, delta_S2S, delta_WS,
                       event_id, site_id)
  }


  if(missing_percent > 0){
    sample_event <- sample(unique(data$event_id), size = num_event, replace = FALSE)
    sample_site <- sample(unique(data$site_id), size = num_site, replace = FALSE)

    prob_event <- as.matrix(cumsum(rep(2/num_event/(num_event+1), num_event)))
    prob_site <- t(as.matrix(cumsum(rep(2/num_site/(num_site+1), num_site))))
    # the sum of probabilities in the matrix is one
    prob_matrix <- prob_event %*% prob_site
    probs <- c(t(prob_matrix[sapply(1:num_event, function(x) which(sample_event == x)),
                             sapply(1:num_site, function(x) which(sample_site == x))]))

    missing_idx <- sample(seq(1, nrow(data)), size = missing_percent*nrow(data), prob = probs)
    data_unbalanced <- data[-c(missing_idx),]
    return(data_unbalanced)
  }

  return(data)
}
