#' Generate simulation data
#'
#' @param num_eq The integer to specify the number of earthquakes.
#' @param num_site The integer to specify the number of earthquake stations.
#' @param eta_eq_sd The numeric value to specify the standard deviation of earthquake terms.
#' @param eta_site_sd The numeric value specify the standard deviation of station terms.
#' @param eta_noise_sd The numeric value specify the standard deviation of noise terms.
#' @param path_term A logical indicator for whether to generate path term.
#' @param eta_path_sd The numeric value to specify the standard deviation of path terms.
#' @param num_eq_cluster The integer to specify the number of earthquakes clusters.
#' @param num_site_cluster The integer to specify the number of station clusters.
#' @param missing_percent A decimal between 0 and 1, indicating the percentage of
#'                        missingness generated by missing completely at random(MCAR).
#'
#' @return A data frame containing the full simulation dataset.
#' @export
#'
#' @examples
#' gm_data <- dgp(num_eq = 10, num_site = 20,
#'             eta_eq_sd = 1, eta_site_sd = 1, eta_noise_sd = 1,
#'             path_term = TRUE, eta_path_sd = 1,
#'             num_eq_cluster = 4, num_site_cluster = 5,
#'             missing_percent = 0.1)
dgp <- function(num_eq, num_site,
                eta_eq_sd = 1, eta_site_sd = 1, eta_noise_sd = 1,
                path_term = FALSE, eta_path_sd = NULL,
                num_eq_cluster = NULL, num_site_cluster = NULL,
                missing_percent = 0){

  eta_eq <- rep(rnorm(num_eq, mean=0, sd=eta_eq_sd), each = num_site)
  earthquake_id <- as.factor(rep(1:num_eq, each = num_site))


  eta_site <- rep(rnorm(num_site, mean = 0, sd = eta_site_sd), num_eq)
  site_id <- as.factor(rep(1:num_site, num_eq))

  noise <- rnorm(num_eq*num_site, mean=0, sd=eta_noise_sd)

  r <- eta_eq + eta_site + noise

  if(path_term == TRUE){
    eq_cluster <- sample(1:num_eq_cluster, num_eq, replace = TRUE)
    eq_cluster_id <- sapply(earthquake_id, function(x) eq_cluster[x])

    site_cluster <- sample(1:num_site_cluster, num_site, replace = TRUE)
    eq_site_id <- sapply(site_id, function(x) site_cluster[x])

    path_id <- as.numeric(factor(paste(eq_cluster_id,eq_site_id)))
    path_value <- rnorm(max(path_id), mean = 0, sd = eta_path_sd)
    eta_path <- sapply(path_id, function(x) path_value[x])
    path_id <- as.factor(path_id)

    r <- eta_eq + eta_site + eta_path + noise
  }

  if(path_term == TRUE){
    data <- data.frame(r, eta_eq, eta_site, eta_path, noise,
               earthquake_id, site_id, path_id)
  }else{
    data <- data.frame(r, eta_eq, eta_site, noise,
                       earthquake_id, site_id)
  }


  if(missing_percent > 0){
    sample_eq <- sample(unique(data$earthquake_id), size = num_eq, replace = FALSE)
    sample_site <- sample(unique(data$site_id), size = num_site, replace = FALSE)

    prob_eq <- as.matrix(cumsum(rep(2/num_eq/(num_eq+1), num_eq)))
    prob_site <- t(as.matrix(cumsum(rep(2/num_site/(num_site+1), num_site))))
    # the sum of probabilities in the matrix is one
    prob_matrix <- prob_eq %*% prob_site
    probs <- c(t(prob_matrix[sapply(1:num_eq, function(x) which(sample_eq == x)),
                             sapply(1:num_site, function(x) which(sample_site == x))]))

    missing_idx <- sample(seq(1,nrow(data)), size = missing_percent*nrow(data), prob = probs)
    data_unbalanced <- data[-c(missing_idx),]
    return(data_unbalanced)
  }

  return(data)
}
